import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/legal/disclaimer")({
  head: () => ({
    meta: [
      { title: "Medical Disclaimer | TrialFinderUS" },
      { name: "description", content: "Important medical, informational, and liability disclaimers for users of TrialFinderUS." },
    ],
    links: [{ rel: "canonical", href: "/legal/disclaimer" }],
  }),
  component: Page,
});

function Page() {
  return (
    <article className="container mx-auto max-w-3xl px-4 py-12 prose prose-sm dark:prose-invert">
      <h1>Medical Disclaimer</h1>
      <p><em>Last updated: June 27, 2026</em></p>
      <h2>Not medical advice</h2>
      <p>
        TrialFinderUS is an independent informational directory of clinical trials and research studies. The content on
        this site, including trial descriptions, eligibility criteria, AI-generated plain-language summaries, and any
        other information, is provided for general educational purposes only. It is <strong>not medical advice,
        diagnosis, or treatment</strong>, and is not a substitute for the professional judgment of a licensed
        physician or other qualified healthcare provider.
      </p>
      <h2>No doctor-patient relationship</h2>
      <p>
        Use of TrialFinderUS does not create a doctor-patient relationship between you and TrialFinderUS, its
        operators, employees, contractors, or any clinic, sponsor, investigator, or researcher whose trials appear on
        this site.
      </p>
      <h2>No recommendations</h2>
      <p>
        We do not recommend, endorse, or guarantee any specific clinical trial, treatment, drug, device, procedure,
        therapy, sponsor, investigator, or research site. The order in which trials, clinics, or sponsors appear is
        based on data quality and engagement signals and may include paid placement; it should not be interpreted as
        an endorsement.
      </p>
      <h2>Eligibility pre-screening</h2>
      <p>
        Our "Check My Eligibility" tool is a stateless pre-screening questionnaire intended only to help you decide
        whether to contact a research site. It is not a clinical assessment, does not diagnose any condition, and
        does not guarantee that you will or will not be enrolled in any trial. Final eligibility decisions are made
        exclusively by the trial's investigators.
      </p>
      <h2>AI-generated summaries</h2>
      <p>
        Plain-language summaries generated by AI may contain errors, omissions, or oversimplifications. Always read
        the original trial protocol and consult a qualified medical professional before relying on any information.
      </p>
      <h2>No emergency services</h2>
      <p>
        TrialFinderUS is not for medical emergencies. If you are experiencing a medical emergency, call 911 or your
        local emergency number immediately.
      </p>
      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, TrialFinderUS and its operators disclaim all warranties, express or
        implied, regarding the accuracy, completeness, or reliability of any information on this site, and shall not
        be liable for any damages of any kind arising from the use of, or inability to use, this site.
      </p>
      <h2>Data source</h2>
      <p>
        Trial information is aggregated from ClinicalTrials.gov, a service of the U.S. National Library of Medicine.
        TrialFinderUS is independent and not affiliated with the U.S. Government, NIH, or ClinicalTrials.gov.
      </p>
    </article>
  );
}
