/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatesIndexRouteImport } from './routes/states.index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as ClinicsIndexRouteImport } from './routes/clinics.index'
import { Route as StudiesNctIdRouteImport } from './routes/studies.$nctId'
import { Route as StatesStateSlugRouteImport } from './routes/states.$stateSlug'
import { Route as SponsorsSlugRouteImport } from './routes/sponsors.$slug'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as PhasePhaseRouteImport } from './routes/phase.$phase'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as ClinicsAuthRouteImport } from './routes/clinics.auth'
import { Route as ClinicsSlugRouteImport } from './routes/clinics.$slug'
import { Route as CitiesCitySlugRouteImport } from './routes/cities.$citySlug'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'
import { Route as AuthenticatedPortalClaimRouteImport } from './routes/_authenticated/portal.claim'
import { Route as AuthenticatedPortalBillingRouteImport } from './routes/_authenticated/portal.billing'
import { Route as AuthenticatedPortalClinicIdRouteImport } from './routes/_authenticated/portal.clinic.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesIndexRoute = StatesIndexRouteImport.update({
  id: '/states/',
  path: '/states/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsIndexRoute = ClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiesNctIdRoute = StudiesNctIdRouteImport.update({
  id: '/studies/$nctId',
  path: '/studies/$nctId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesStateSlugRoute = StatesStateSlugRouteImport.update({
  id: '/states/$stateSlug',
  path: '/states/$stateSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsSlugRoute = SponsorsSlugRouteImport.update({
  id: '/sponsors/$slug',
  path: '/sponsors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasePhaseRoute = PhasePhaseRouteImport.update({
  id: '/phase/$phase',
  path: '/phase/$phase',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsAuthRoute = ClinicsAuthRouteImport.update({
  id: '/clinics/auth',
  path: '/clinics/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsSlugRoute = ClinicsSlugRouteImport.update({
  id: '/clinics/$slug',
  path: '/clinics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCitySlugRoute = CitiesCitySlugRouteImport.update({
  id: '/cities/$citySlug',
  path: '/cities/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalClaimRoute =
  AuthenticatedPortalClaimRouteImport.update({
    id: '/claim',
    path: '/claim',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBillingRoute =
  AuthenticatedPortalBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalClinicIdRoute =
  AuthenticatedPortalClinicIdRouteImport.update({
    id: '/clinic/$id',
    path: '/clinic/$id',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recruiting': typeof RecruitingRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinics/auth': typeof ClinicsAuthRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/phase/$phase': typeof PhasePhaseRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/sponsors/$slug': typeof SponsorsSlugRoute
  '/states/$stateSlug': typeof StatesStateSlugRoute
  '/studies/$nctId': typeof StudiesNctIdRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/states/': typeof StatesIndexRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/claim': typeof AuthenticatedPortalClaimRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/portal/clinic/$id': typeof AuthenticatedPortalClinicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/recruiting': typeof RecruitingRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinics/auth': typeof ClinicsAuthRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/phase/$phase': typeof PhasePhaseRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/sponsors/$slug': typeof SponsorsSlugRoute
  '/states/$stateSlug': typeof StatesStateSlugRoute
  '/studies/$nctId': typeof StudiesNctIdRoute
  '/clinics': typeof ClinicsIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/states': typeof StatesIndexRoute
  '/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/portal/claim': typeof AuthenticatedPortalClaimRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/portal/clinic/$id': typeof AuthenticatedPortalClinicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/recruiting': typeof RecruitingRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/cities/$citySlug': typeof CitiesCitySlugRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinics/auth': typeof ClinicsAuthRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/phase/$phase': typeof PhasePhaseRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/sponsors/$slug': typeof SponsorsSlugRoute
  '/states/$stateSlug': typeof StatesStateSlugRoute
  '/studies/$nctId': typeof StudiesNctIdRoute
  '/clinics/': typeof ClinicsIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/states/': typeof StatesIndexRoute
  '/_authenticated/portal/billing': typeof AuthenticatedPortalBillingRoute
  '/_authenticated/portal/claim': typeof AuthenticatedPortalClaimRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/portal/clinic/$id': typeof AuthenticatedPortalClinicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/recruiting'
    | '/search'
    | '/admin'
    | '/portal'
    | '/cities/$citySlug'
    | '/clinics/$slug'
    | '/clinics/auth'
    | '/conditions/$slug'
    | '/learn/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/phase/$phase'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/sponsors/$slug'
    | '/states/$stateSlug'
    | '/studies/$nctId'
    | '/clinics/'
    | '/conditions/'
    | '/learn/'
    | '/sponsors/'
    | '/states/'
    | '/portal/billing'
    | '/portal/claim'
    | '/api/public/seed-admin'
    | '/portal/'
    | '/portal/clinic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/recruiting'
    | '/search'
    | '/admin'
    | '/cities/$citySlug'
    | '/clinics/$slug'
    | '/clinics/auth'
    | '/conditions/$slug'
    | '/learn/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/phase/$phase'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/sponsors/$slug'
    | '/states/$stateSlug'
    | '/studies/$nctId'
    | '/clinics'
    | '/conditions'
    | '/learn'
    | '/sponsors'
    | '/states'
    | '/portal/billing'
    | '/portal/claim'
    | '/api/public/seed-admin'
    | '/portal'
    | '/portal/clinic/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/recruiting'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/cities/$citySlug'
    | '/clinics/$slug'
    | '/clinics/auth'
    | '/conditions/$slug'
    | '/learn/$slug'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/phase/$phase'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/sponsors/$slug'
    | '/states/$stateSlug'
    | '/studies/$nctId'
    | '/clinics/'
    | '/conditions/'
    | '/learn/'
    | '/sponsors/'
    | '/states/'
    | '/_authenticated/portal/billing'
    | '/_authenticated/portal/claim'
    | '/api/public/seed-admin'
    | '/_authenticated/portal/'
    | '/_authenticated/portal/clinic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecruitingRoute: typeof RecruitingRoute
  SearchRoute: typeof SearchRoute
  CitiesCitySlugRoute: typeof CitiesCitySlugRoute
  ClinicsSlugRoute: typeof ClinicsSlugRoute
  ClinicsAuthRoute: typeof ClinicsAuthRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PhasePhaseRoute: typeof PhasePhaseRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  SponsorsSlugRoute: typeof SponsorsSlugRoute
  StatesStateSlugRoute: typeof StatesStateSlugRoute
  StudiesNctIdRoute: typeof StudiesNctIdRoute
  ClinicsIndexRoute: typeof ClinicsIndexRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
  StatesIndexRoute: typeof StatesIndexRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/': {
      id: '/states/'
      path: '/states'
      fullPath: '/states/'
      preLoaderRoute: typeof StatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/': {
      id: '/clinics/'
      path: '/clinics'
      fullPath: '/clinics/'
      preLoaderRoute: typeof ClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studies/$nctId': {
      id: '/studies/$nctId'
      path: '/studies/$nctId'
      fullPath: '/studies/$nctId'
      preLoaderRoute: typeof StudiesNctIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states/$stateSlug': {
      id: '/states/$stateSlug'
      path: '/states/$stateSlug'
      fullPath: '/states/$stateSlug'
      preLoaderRoute: typeof StatesStateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/$slug': {
      id: '/sponsors/$slug'
      path: '/sponsors/$slug'
      fullPath: '/sponsors/$slug'
      preLoaderRoute: typeof SponsorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase/$phase': {
      id: '/phase/$phase'
      path: '/phase/$phase'
      fullPath: '/phase/$phase'
      preLoaderRoute: typeof PhasePhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/auth': {
      id: '/clinics/auth'
      path: '/clinics/auth'
      fullPath: '/clinics/auth'
      preLoaderRoute: typeof ClinicsAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics/$slug': {
      id: '/clinics/$slug'
      path: '/clinics/$slug'
      fullPath: '/clinics/$slug'
      preLoaderRoute: typeof ClinicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$citySlug': {
      id: '/cities/$citySlug'
      path: '/cities/$citySlug'
      fullPath: '/cities/$citySlug'
      preLoaderRoute: typeof CitiesCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/claim': {
      id: '/_authenticated/portal/claim'
      path: '/claim'
      fullPath: '/portal/claim'
      preLoaderRoute: typeof AuthenticatedPortalClaimRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/billing': {
      id: '/_authenticated/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof AuthenticatedPortalBillingRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/clinic/$id': {
      id: '/_authenticated/portal/clinic/$id'
      path: '/clinic/$id'
      fullPath: '/portal/clinic/$id'
      preLoaderRoute: typeof AuthenticatedPortalClinicIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalBillingRoute: typeof AuthenticatedPortalBillingRoute
  AuthenticatedPortalClaimRoute: typeof AuthenticatedPortalClaimRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalClinicIdRoute: typeof AuthenticatedPortalClinicIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalBillingRoute: AuthenticatedPortalBillingRoute,
  AuthenticatedPortalClaimRoute: AuthenticatedPortalClaimRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalClinicIdRoute: AuthenticatedPortalClinicIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  RecruitingRoute: RecruitingRoute,
  SearchRoute: SearchRoute,
  CitiesCitySlugRoute: CitiesCitySlugRoute,
  ClinicsSlugRoute: ClinicsSlugRoute,
  ClinicsAuthRoute: ClinicsAuthRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PhasePhaseRoute: PhasePhaseRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  SponsorsSlugRoute: SponsorsSlugRoute,
  StatesStateSlugRoute: StatesStateSlugRoute,
  StudiesNctIdRoute: StudiesNctIdRoute,
  ClinicsIndexRoute: ClinicsIndexRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
  StatesIndexRoute: StatesIndexRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
